# -*- coding: utf-8 -*-
"""LicensePlates.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nM7sz7ACAFDnYI-Uh8Z_zKSgbaQBgf5p
"""

import yolov5

# load model
model = yolov5.load('keremberke/yolov5m-license-plate')

# set model parameters
model.conf = 0.4  # NMS confidence threshold
model.iou = 0.45  # NMS IoU threshold
model.agnostic = False  # NMS class-agnostic
model.multi_label = False  # NMS multiple labels per box
model.max_det = 1000  # maximum number of detections per image

